name: Main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.x

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
