name: Release Drafter
on: [push]
jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    # Inception: install goaction from current code and
    # update the action files.
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.19.x